In [1]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

In [2]:
#part A
x_arr=np.array([1.2,1.1,0.5,1.5,1.13,+0.8]).reshape(-1,1)

In [3]:
# print('X_arr=:',x_arr.reshape(1,-1))

In [4]:
epsilon=0.13
W=-epsilon*np.ones((len(x_arr),len(x_arr)))
for i in range(len(x_arr)):
  W[i,i]=1
W

array([[1.00, -0.13, -0.13, -0.13, -0.13, -0.13],
       [-0.13, 1.00, -0.13, -0.13, -0.13, -0.13],
       [-0.13, -0.13, 1.00, -0.13, -0.13, -0.13],
       [-0.13, -0.13, -0.13, 1.00, -0.13, -0.13],
       [-0.13, -0.13, -0.13, -0.13, 1.00, -0.13],
       [-0.13, -0.13, -0.13, -0.13, -0.13, 1.00]])

In [5]:
def relu(x):
  f=np.zeros(len(x))
  for j in range(len(x)):
    if x[j]>0:
      f[j]=x[j]
    else :
      f[j]=0
  return f

# Part 1

In [6]:
def Maxnet(x_arr,W):
  a_old=x_arr.copy()
  v=np.count_nonzero(x_arr)
  counter=0
  while(v>1):
    counter+=1
    # print(counter,v)
    print(counter,'st iteration:')
    a_new=relu(np.matmul(W,a_old))
    print('New vector ',a_new)
    a_old=a_new.copy()
    v=np.count_nonzero(a_new)
  return a_new

In [7]:
a_new=Maxnet(x_arr,W)

1 st iteration:
New vector  [0.55 0.43 0.00 0.89 0.47 0.09]
2 st iteration:
New vector  [0.30 0.17 0.00 0.68 0.21 0.00]
3 st iteration:
New vector  [0.16 0.02 0.00 0.60 0.06 0.00]
4 st iteration:
New vector  [0.07 0.00 0.00 0.56 0.00 0.00]
5 st iteration:
New vector  [0.00 0.00 0.00 0.55 0.00 0.00]
6 st iteration:
New vector  [0.00 0.00 0.00 0.55 0.00 0.00]


In [8]:
index=np.where(a_new!=0)[0]
x_max1=x_arr[index][0]
print('Maximum  Value of x_arr:\n ',x_arr,'is =',x_max1)

Maximum  Value of x_arr:
  [[1.20]
 [1.10]
 [0.50]
 [1.50]
 [1.13]
 [0.80]] is = [1.50]


# Part 2

In [9]:
x_arr_new=[1.2,1.1,0.5,-1.5,1.13,-0.8]

In [10]:
# print('X_arr=:',x_arr_new)

In [11]:
a_new1=Maxnet(x_arr_new,W)        #for x

1 st iteration:
New vector  [1.14 1.03 0.35 0.00 1.06 0.00]
2 st iteration:
New vector  [0.83 0.70 0.00 0.00 0.74 0.00]
3 st iteration:
New vector  [0.64 0.49 0.00 0.00 0.54 0.00]
4 st iteration:
New vector  [0.50 0.34 0.00 0.00 0.39 0.00]
5 st iteration:
New vector  [0.41 0.23 0.00 0.00 0.28 0.00]
6 st iteration:
New vector  [0.34 0.14 0.00 0.00 0.20 0.00]
7 st iteration:
New vector  [0.30 0.07 0.00 0.00 0.14 0.00]
8 st iteration:
New vector  [0.27 0.01 0.00 0.00 0.09 0.00]
9 st iteration:
New vector  [0.26 0.00 0.00 0.00 0.05 0.00]
10 st iteration:
New vector  [0.26 0.00 0.00 0.00 0.02 0.00]
11 st iteration:
New vector  [0.25 0.00 0.00 0.00 0.00 0.00]


In [12]:
index=np.where(a_new1!=0)[0]
v_plus=x_arr_new[index[0]]

In [13]:
x_arr_new_prime=np.multiply(x_arr_new,-1)
a_new2=Maxnet(x_arr_new_prime,W)  

1 st iteration:
New vector  [0.00 0.00 0.00 1.91 0.00 1.12]
2 st iteration:
New vector  [0.00 0.00 0.00 1.76 0.00 0.87]
3 st iteration:
New vector  [0.00 0.00 0.00 1.65 0.00 0.64]
4 st iteration:
New vector  [0.00 0.00 0.00 1.57 0.00 0.42]
5 st iteration:
New vector  [0.00 0.00 0.00 1.51 0.00 0.22]
6 st iteration:
New vector  [0.00 0.00 0.00 1.48 0.00 0.02]
7 st iteration:
New vector  [0.00 0.00 0.00 1.48 0.00 0.00]


In [14]:
index=np.where(a_new2!=0)[0]
v_minus=-x_arr_new[index[0]]

In [15]:
v=np.append(v_plus,v_minus)

In [16]:
w_2=np.array([1 ,-0.5,-0.5,1 ]).reshape((2,2))
w_2

array([[1.00, -0.50],
       [-0.50, 1.00]])

In [17]:
a_new_final=Maxnet(v,w_2)  

1 st iteration:
New vector  [0.45 0.90]
2 st iteration:
New vector  [0.00 0.68]


In [18]:
index=np.where(a_new_final!=0)[0]
x_max2=v[index][0]
print('Maximum absolute Value of x_arr: ',x_arr_new,'is =',x_max2)

Maximum absolute Value of x_arr:  [1.2, 1.1, 0.5, -1.5, 1.13, -0.8] is = 1.5
